spring.application.name=unifiedeats2

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/tech_challenge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tech}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tech123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.tool.schema=DEBUG